// State de productos
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';
export const REGISTRAR_USUARIO = 'REGISTRAR_USUARIO';
export const VALIDDAR_USUARIO = 'VALIDAR_USUARIO';

//State para el pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIOAR_PRODUCTO';
export const CONFIRMAR_PEDIDO_PRODUCTO = 'CONFIRMAR_PEDIDO_PRODUCTO';
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';

//State para favoritos
export const GUARDAR_FAVORITOS = 'GUARDAR_FAVORITOS';