// State de productos
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';
export const REGISTRAR_USUARIO = 'REGISTRAR_USUARIO';
export const VALIDDAR_USUARIO = 'VALIDAR_USUARIO';
export const ELIMINAR_USUARIO ='ELIMINAR_USUARIO';

//State para el pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIOAR_PRODUCTO';
export const CONFIRMAR_PEDIDO_PRODUCTO = 'CONFIRMAR_PEDIDO_PRODUCTO';
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const COMPRA_REALIZADA = 'COMPRA_REALIZADA';
export const ELIMINAR_PEDIDOS = 'ELIMINAR_PEDIDOS'

//State para favoritos
export const GUARDAR_FAVORITOS = 'GUARDAR_FAVORITOS';
export const OBTENER_FAVORITOS_STORAGE = 'OBTENER_FAVORITOS_STORAGE';
export const ELIMINAR_FAVORITOS ='ELIMINAR_FAVORITOS';
