// State de productos
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';

//State para el pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIOAR_PRODUCTO';
export const CONFIRMAR_PEDIDO_PRODUCTO = 'CONFIRMAR_PEDIDO_PRODUCTO';
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';